#!/bin/sh
#!/bin/sh
cd os
cargo build --release #--manifest-path os/Cargo.toml
rust-objcopy --strip-all target/riscv64gc-unknown-none-elf/release/rcore -O binary target/riscv64gc-unknown-none-elf/release/rcore.bin
# type ctrl+a c in terminal
# QEMU 参数列表 https://www.qemu.org/docs/master/system/invocation.html
# 选择仿真机器为virt，启动一个VNC server，使用 rustsbi-qemu 作为 BIOS firmware
# 声明一个generic loader 作为 device，装载地址为 0x80200000
qemu-system-riscv64 \
    -machine virt \
    -vnc :0 \
    -nographic \
    -bios ../bootloader/rustsbi-qemu.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/release/rcore.bin,addr=0x80200000 #-s -S

# 查看 loader 的 options qemu-system-riscv64 -device loader,help