#!/bin/sh
#!/bin/sh
cargo build
rust-objcopy --strip-all target/riscv64gc-unknown-none-elf/debug/rcore -O binary target/riscv64gc-unknown-none-elf/debug/rcore.bin
# type ctrl+a c in terminal
qemu-system-riscv64 \
    -machine virt \
    -vnc :0 \
    -nographic \
    -bios bootloader/rustsbi-qemu.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/debug/rcore.bin,addr=0x80200000
